export type Gender = 'male' | 'female'
export type HairColor =
  | 'black'
  | 'brown'
  | 'blonde'
  | 'red'
  | 'gray'
  | 'white'
  | 'none'
export type HairLength = 'short' | 'long' | 'bald'
export type EyeColor = 'brown' | 'blue' | 'green'
export type SkinTone = 'light' | 'medium' | 'dark'
export type Age = 'young' | 'adult' | 'elderly'

export interface Character {
  id: number
  name: string
  gender: Gender
  hairColor: HairColor
  hairLength: HairLength
  eyeColor: EyeColor
  glasses: boolean
  hat: boolean
  hatColor: string | null
  beard: boolean
  mustache: boolean
  earrings: boolean
  freckles: boolean
  skinTone: SkinTone
  age: Age
  smile: boolean
}

export const CHARACTERS: Character[] = [
  {
    id: 1,
    name: 'Alex',
    gender: 'male',
    hairColor: 'brown',
    hairLength: 'short',
    eyeColor: 'blue',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: true,
  },
  {
    id: 2,
    name: 'Beth',
    gender: 'female',
    hairColor: 'blonde',
    hairLength: 'long',
    eyeColor: 'green',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: true,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: true,
  },
  {
    id: 3,
    name: 'Carlos',
    gender: 'male',
    hairColor: 'black',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: true,
    hat: true,
    hatColor: '#2563eb',
    beard: false,
    mustache: true,
    earrings: false,
    freckles: false,
    skinTone: 'medium',
    age: 'adult',
    smile: false,
  },
  {
    id: 4,
    name: 'Diana',
    gender: 'female',
    hairColor: 'red',
    hairLength: 'long',
    eyeColor: 'blue',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: true,
    freckles: true,
    skinTone: 'light',
    age: 'young',
    smile: true,
  },
  {
    id: 5,
    name: 'Ethan',
    gender: 'male',
    hairColor: 'blonde',
    hairLength: 'short',
    eyeColor: 'blue',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: true,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: true,
  },
  {
    id: 6,
    name: 'Fatima',
    gender: 'female',
    hairColor: 'black',
    hairLength: 'long',
    eyeColor: 'brown',
    glasses: false,
    hat: true,
    hatColor: '#dc2626',
    beard: false,
    mustache: false,
    earrings: true,
    freckles: false,
    skinTone: 'dark',
    age: 'adult',
    smile: true,
  },
  {
    id: 7,
    name: 'George',
    gender: 'male',
    hairColor: 'gray',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: true,
    mustache: true,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'elderly',
    smile: false,
  },
  {
    id: 8,
    name: 'Hannah',
    gender: 'female',
    hairColor: 'brown',
    hairLength: 'short',
    eyeColor: 'green',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: true,
    freckles: true,
    skinTone: 'medium',
    age: 'young',
    smile: true,
  },
  {
    id: 9,
    name: 'Ibrahim',
    gender: 'male',
    hairColor: 'black',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: true,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'dark',
    age: 'adult',
    smile: true,
  },
  {
    id: 10,
    name: 'Jasmine',
    gender: 'female',
    hairColor: 'brown',
    hairLength: 'long',
    eyeColor: 'brown',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'medium',
    age: 'adult',
    smile: true,
  },
  {
    id: 11,
    name: 'Kenji',
    gender: 'male',
    hairColor: 'none',
    hairLength: 'bald',
    eyeColor: 'brown',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: true,
    earrings: false,
    freckles: false,
    skinTone: 'medium',
    age: 'adult',
    smile: false,
  },
  {
    id: 12,
    name: 'Luna',
    gender: 'female',
    hairColor: 'white',
    hairLength: 'long',
    eyeColor: 'blue',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: true,
    freckles: false,
    skinTone: 'light',
    age: 'elderly',
    smile: true,
  },
  {
    id: 13,
    name: 'Marcus',
    gender: 'male',
    hairColor: 'brown',
    hairLength: 'short',
    eyeColor: 'green',
    glasses: false,
    hat: true,
    hatColor: '#16a34a',
    beard: false,
    mustache: false,
    earrings: false,
    freckles: true,
    skinTone: 'light',
    age: 'young',
    smile: true,
  },
  {
    id: 14,
    name: 'Nia',
    gender: 'female',
    hairColor: 'black',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: true,
    freckles: false,
    skinTone: 'dark',
    age: 'adult',
    smile: false,
  },
  {
    id: 15,
    name: 'Oscar',
    gender: 'male',
    hairColor: 'red',
    hairLength: 'short',
    eyeColor: 'blue',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: true,
    mustache: false,
    earrings: false,
    freckles: true,
    skinTone: 'light',
    age: 'adult',
    smile: true,
  },
  {
    id: 16,
    name: 'Priya',
    gender: 'female',
    hairColor: 'black',
    hairLength: 'long',
    eyeColor: 'brown',
    glasses: false,
    hat: true,
    hatColor: '#9333ea',
    beard: false,
    mustache: false,
    earrings: true,
    freckles: false,
    skinTone: 'medium',
    age: 'young',
    smile: true,
  },
  {
    id: 17,
    name: 'Quincy',
    gender: 'male',
    hairColor: 'white',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: true,
    earrings: false,
    freckles: false,
    skinTone: 'dark',
    age: 'elderly',
    smile: false,
  },
  {
    id: 18,
    name: 'Rosa',
    gender: 'female',
    hairColor: 'gray',
    hairLength: 'long',
    eyeColor: 'green',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: true,
    freckles: true,
    skinTone: 'light',
    age: 'elderly',
    smile: true,
  },
  {
    id: 19,
    name: 'Sam',
    gender: 'male',
    hairColor: 'blonde',
    hairLength: 'short',
    eyeColor: 'green',
    glasses: false,
    hat: true,
    hatColor: '#eab308',
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'young',
    smile: false,
  },
  {
    id: 20,
    name: 'Tara',
    gender: 'female',
    hairColor: 'brown',
    hairLength: 'long',
    eyeColor: 'blue',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: true,
    skinTone: 'medium',
    age: 'adult',
    smile: false,
  },
  {
    id: 21,
    name: 'Uma',
    gender: 'female',
    hairColor: 'none',
    hairLength: 'bald',
    eyeColor: 'brown',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: true,
    freckles: false,
    skinTone: 'dark',
    age: 'adult',
    smile: true,
  },
  {
    id: 22,
    name: 'Victor',
    gender: 'male',
    hairColor: 'gray',
    hairLength: 'long',
    eyeColor: 'blue',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: true,
    mustache: true,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'elderly',
    smile: false,
  },
  {
    id: 23,
    name: 'Wren',
    gender: 'female',
    hairColor: 'red',
    hairLength: 'short',
    eyeColor: 'green',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: true,
    skinTone: 'light',
    age: 'young',
    smile: true,
  },
  {
    id: 24,
    name: 'Xavier',
    gender: 'male',
    hairColor: 'black',
    hairLength: 'long',
    eyeColor: 'brown',
    glasses: false,
    hat: true,
    hatColor: '#1f2937',
    beard: false,
    mustache: false,
    earrings: true,
    freckles: false,
    skinTone: 'medium',
    age: 'adult',
    smile: false,
  },
]
