export type Gender = 'male' | 'female'
export type HairColor =
  | 'black'
  | 'brown'
  | 'blonde'
  | 'red'
  | 'gray'
  | 'white'
  | 'none'
export type HairLength = 'short' | 'long' | 'bald'
export type EyeColor = 'brown' | 'blue' | 'green'
export type SkinTone = 'light' | 'medium' | 'dark'
export type Age = 'young' | 'adult' | 'elderly'

export interface Character {
  id: number
  name: string
  gender: Gender
  hairColor: HairColor
  hairLength: HairLength
  eyeColor: EyeColor
  glasses: boolean
  hat: boolean
  hatColor: string | null
  beard: boolean
  mustache: boolean
  earrings: boolean
  freckles: boolean
  skinTone: SkinTone
  age: Age
  smile: boolean
  bigNose: boolean
}

/**
 * 24 characters inspired by the classic 1987 Milton Bradley / Hasbro Guess Who?
 * lineup. Names and feature combinations follow the original cards; portraits
 * are original procedural-SVG renderings (not pixel reproductions).
 */
export const CHARACTERS: Character[] = [
  {
    id: 1,
    name: 'Alex',
    gender: 'male',
    hairColor: 'none',
    hairLength: 'bald',
    eyeColor: 'brown',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: false,
    bigNose: true,
  },
  {
    id: 2,
    name: 'Alfred',
    gender: 'male',
    hairColor: 'red',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: true,
    earrings: false,
    freckles: true,
    skinTone: 'light',
    age: 'adult',
    smile: false,
    bigNose: false,
  },
  {
    id: 3,
    name: 'Anita',
    gender: 'female',
    hairColor: 'blonde',
    hairLength: 'long',
    eyeColor: 'blue',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: true,
    bigNose: false,
  },
  {
    id: 4,
    name: 'Anne',
    gender: 'female',
    hairColor: 'black',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'young',
    smile: true,
    bigNose: false,
  },
  {
    id: 5,
    name: 'Bernard',
    gender: 'male',
    hairColor: 'brown',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: false,
    hat: true,
    hatColor: '#7c4a1e',
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: false,
    bigNose: true,
  },
  {
    id: 6,
    name: 'Bill',
    gender: 'male',
    hairColor: 'red',
    hairLength: 'bald',
    eyeColor: 'blue',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: true,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: true,
    bigNose: false,
  },
  {
    id: 7,
    name: 'Charles',
    gender: 'male',
    hairColor: 'brown',
    hairLength: 'short',
    eyeColor: 'blue',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: true,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: false,
    bigNose: false,
  },
  {
    id: 8,
    name: 'Claire',
    gender: 'female',
    hairColor: 'red',
    hairLength: 'short',
    eyeColor: 'blue',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: true,
    skinTone: 'light',
    age: 'young',
    smile: true,
    bigNose: false,
  },
  {
    id: 9,
    name: 'David',
    gender: 'male',
    hairColor: 'blonde',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: true,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: false,
    bigNose: false,
  },
  {
    id: 10,
    name: 'Eric',
    gender: 'male',
    hairColor: 'blonde',
    hairLength: 'short',
    eyeColor: 'blue',
    glasses: false,
    hat: true,
    hatColor: '#1e4ed8',
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'young',
    smile: true,
    bigNose: false,
  },
  {
    id: 11,
    name: 'Frans',
    gender: 'male',
    hairColor: 'red',
    hairLength: 'short',
    eyeColor: 'blue',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: true,
    skinTone: 'light',
    age: 'adult',
    smile: true,
    bigNose: false,
  },
  {
    id: 12,
    name: 'George',
    gender: 'male',
    hairColor: 'white',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'elderly',
    smile: false,
    bigNose: false,
  },
  {
    id: 13,
    name: 'Herman',
    gender: 'male',
    hairColor: 'none',
    hairLength: 'bald',
    eyeColor: 'blue',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: true,
    bigNose: false,
  },
  {
    id: 14,
    name: 'Joe',
    gender: 'male',
    hairColor: 'brown',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: true,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: false,
    bigNose: false,
  },
  {
    id: 15,
    name: 'Maria',
    gender: 'female',
    hairColor: 'brown',
    hairLength: 'long',
    eyeColor: 'brown',
    glasses: false,
    hat: true,
    hatColor: '#dc2626',
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'medium',
    age: 'adult',
    smile: true,
    bigNose: false,
  },
  {
    id: 16,
    name: 'Max',
    gender: 'male',
    hairColor: 'black',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: true,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: false,
    bigNose: false,
  },
  {
    id: 17,
    name: 'Paul',
    gender: 'male',
    hairColor: 'white',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: true,
    mustache: true,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'elderly',
    smile: false,
    bigNose: false,
  },
  {
    id: 18,
    name: 'Peter',
    gender: 'male',
    hairColor: 'blonde',
    hairLength: 'short',
    eyeColor: 'blue',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'young',
    smile: true,
    bigNose: false,
  },
  {
    id: 19,
    name: 'Philip',
    gender: 'male',
    hairColor: 'black',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: true,
    mustache: true,
    earrings: false,
    freckles: false,
    skinTone: 'dark',
    age: 'adult',
    smile: false,
    bigNose: false,
  },
  {
    id: 20,
    name: 'Richard',
    gender: 'male',
    hairColor: 'brown',
    hairLength: 'bald',
    eyeColor: 'brown',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: true,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: false,
    bigNose: false,
  },
  {
    id: 21,
    name: 'Robert',
    gender: 'male',
    hairColor: 'brown',
    hairLength: 'short',
    eyeColor: 'blue',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: true,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: false,
    bigNose: true,
  },
  {
    id: 22,
    name: 'Sam',
    gender: 'male',
    hairColor: 'white',
    hairLength: 'short',
    eyeColor: 'brown',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'elderly',
    smile: false,
    bigNose: true,
  },
  {
    id: 23,
    name: 'Susan',
    gender: 'female',
    hairColor: 'blonde',
    hairLength: 'short',
    eyeColor: 'blue',
    glasses: false,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: false,
    earrings: true,
    freckles: false,
    skinTone: 'light',
    age: 'young',
    smile: true,
    bigNose: false,
  },
  {
    id: 24,
    name: 'Tom',
    gender: 'male',
    hairColor: 'none',
    hairLength: 'bald',
    eyeColor: 'brown',
    glasses: true,
    hat: false,
    hatColor: null,
    beard: false,
    mustache: true,
    earrings: false,
    freckles: false,
    skinTone: 'light',
    age: 'adult',
    smile: false,
    bigNose: false,
  },
]
